"""discard row from review

Revision ID: 65dbd258c9d7
Revises: f5e82c965221
Create Date: 2024-07-09 21:30:28.078033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65dbd258c9d7'
down_revision: Union[str, None] = 'f5e82c965221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_customer_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_customer_id_fkey', 'reviews', 'users', ['customer_id'], ['user_id'])
    # ### end Alembic commands ###
